name: Deployment

on:
  push:
    branches: [main] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i hexo-cli --location=global
        npm i
        hexo clean
        hexo g
    
    - name: Deploy to Github Pages
      env:
        GIT_NAME: reign12
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/reign12/blog
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git config --global init.defaultBranch pub
        cd ./public && git init && git add .
        git commit -m "Site deployed by GitHub Actions on push. "
        git push --force --quiet "https://$GH_TOKEN@$REPO" pub:pub